### ISSUE TITLE
Describe difference between sbt-play-webpack and sbt-webpack

### ISSUE THREAD

**Issue by benmccann** [stonexx/sbt-play-webpack#1]
Thanks for making this available. One question I had is that I noticed you have an sbt-play-webpack and sbt-webpack both available. I'm curious why there are two separate plugins as I wouldn't have expected that there would be a need to have two

**Comment by stonexx** [comment]
I'm not good at English.

There are two major differences between the two plugins:
- `sbt-play-webpack` was written using `PlayRunHook` in `Playframework`.
- And `sbt-webpack` does not depend on` Playframework`.

thx.

**Comment by benmccann** [comment]
Thanks. That's very helpful!
